[package]
name = "comparative-test"
version = "0.1.0"
edition = "2024"

[dependencies]
egglog.workspace = true
eqlog-runtime.workspace = true
expect-test.workspace = true
oatlog.workspace = true
paste.workspace = true

[lints]
workspace = true
