[package]
name = "oatlog-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
oatlog-core.workspace = true
proc-macro2.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[lints]
workspace = true
