[package]
name = "oatlog-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
egglog.workspace = true
oatlog.workspace = true
regex.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "comparative"
harness = false

[lints]
workspace = true
