[package]
name = "egraph-core"
version = "0.1.0"
edition = "2021"

[dependencies]
educe.workspace = true
proc-macro2.workspace = true
quote.workspace = true
regex.workspace = true
syn.workspace = true

[lints]
workspace = true
