name: "report-ci"
on:
  push:
    paths:
      - '.github/workflows/report.yaml'
      - 'doc/report/**'
      - 'flake.lock'
      - 'flake.nix'
jobs:
  mk-report:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - run: nix run .#mk-report

    - run: |
        gh release delete latest-report-draft --yes --cleanup-tag || true
        gh release create latest-report-draft --prerelease ./report.pdf
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
